#!/bin/zsh
# 0 black
# 1 red
# 2 green
# 3 yellow
# 4 blue
# 5 pink
# 6 cyan
# 9 orange
# black -> white 8 0 10 11 12 14 7 15 

# TEMPERATURE

input=/sys/class/hwmon/hwmon0/temp1_input
[ -s "$input" ] && temperature=$(awk '{printf "%0.f",$1/1000}' "$input")
if [ -n "$temperature" ]; then
  if [ "$temperature" -gt 69 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
  elif [ "$temperature" -gt 62 ]; then modifier="#[fg=colour13,bright]"
  elif [ "$temperature" -gt 54 ]; then modifier="#[fg=colour6]"
  else modifier="#[fg=colour4]"
  fi
  printf " %s%s°#[default]" "$modifier" "$temperature"
fi

# MEMORY

memory=$(free | awk '/buffers\/cache:/ {printf "%.0f", 100*$3/($3 + $4)}')
if [ "$memory" -gt 90 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
elif [ "$memory" -gt 80 ]; then modifier="#[bg=colour3,fg=colour0]"
elif [ "$memory" -gt 70 ]; then modifier="#[fg=colour9]"
else modifier="#[fg=colour2]"
fi
printf " %s%s%%#[default]" "$modifier" "$memory"

# CPU BAR

nbcores=4
divisor=2
usage=$(cat /tmp/cpu_usage)
(( usage = usage * nbcores / divisor ))
(( index = usage / 5 ))
[ $index -gt 19 ] && index=19
bar="                   "
for bari in $(seq $index); do
  bar[$bari]="❚"
done
if [ "$usage" -gt 50 ]; then modifier="#[fg=colour1]"
else modifier="#[fg=colour13]"
fi
printf " %s%s#[default]" "$modifier" "$bar"

# CPU FREQ

if [ -r "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq" ]; then
  chart=""
  for i in 0 1 2 3; do
    read cpu < "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_cur_freq"
    case $cpu in
      "2800000") symbol="█";;
      "2400000") symbol="▇";;
      "2200000") symbol="▆";;
      "2000000") symbol="▅";;
      "1800000") symbol="▄";;
      "1600000") symbol="▃";;
      "1400000") symbol="▂";;
      "1200000") symbol="▁";;
      *) symbol="⎯";;
    esac
    chart="$chart$symbol"
  done
  printf "#[fg=colour10]%s" "$chart"; 
fi

# LOAD AVERAGE

load=$(awk '{print $1}' /proc/loadavg)
printf " %s%.01f#[default]" "#[fg=colour14]" "$load"

# SEPARATOR

#printf " #[fg=magenta]•#[default]"

# FRENCH DATE

#export TZ="Europe/Paris"
printf " #[fg=colour12]⎛$(date +"%a %b %d") $(date +"%H:%M")#[default]"
